---
sidebar: sidebar 
permalink: solutions/anf-oracle.html 
keywords: bluexp automation catalog, netapp automation solutions, azure, azure netapp files, oracle, console 
summary: 이 자동화 솔루션을 사용하여 Azure NetApp Files 볼륨을 프로비저닝하고 사용 가능한 가상 머신에 Oracle을 설치할 수 있습니다. 그런 다음 Oracle은 이 볼륨을 데이터 스토리지에 사용합니다. 
---
= Azure NetApp Files를 사용하여 Oracle을 설치합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
이 자동화 솔루션을 사용하여 Azure NetApp Files 볼륨을 프로비저닝하고 사용 가능한 가상 머신에 Oracle을 설치할 수 있습니다. 그런 다음 Oracle은 이 볼륨을 데이터 스토리지에 사용합니다.

.살펴봅니다
이 솔루션과 함께 제공되는 자동화 코드는 개략적으로 다음과 같은 작업을 수행합니다.

* Azure에서 NetApp 계정을 설정합니다
* Azure에서 스토리지 용량 풀 설정
* 정의에 따라 Azure NetApp Files 볼륨을 프로비저닝합니다
* 마운트 지점을 생성합니다
* Azure NetApp Files 볼륨을 마운트 지점에 마운트합니다
* Linux 서버에 Oracle을 설치합니다
* 수신기 및 데이터베이스를 만듭니다
* 플러그형 데이터베이스(PDB) 만들기
* Listener 및 Oracle 인스턴스를 시작합니다
* 스냅샷을 생성하도록 유틸리티를 설치하고 구성합니다 `azacsnap`


.시작하기 전에
설치를 완료하려면 다음이 필요합니다.

* 다운로드가 필요합니다 https://console.netapp.com/automationCatalog["Azure NetApp Files를 사용하는 Oracle"^] NetApp 콘솔 웹 UI를 통한 자동화 솔루션.  솔루션은 파일로 패키징됩니다. `na_oracle19c_deploy-master.zip` .
* 다음과 같은 특성을 가진 Linux VM:
+
** RHEL 8(Standard_D8s_v3-RHEL-8)
** Azure NetApp Files 프로비저닝에 사용되는 것과 동일한 Azure 가상 네트워크에 배포됩니다


* Azure 계정


자동화 솔루션은 이미지로 제공되며 Docker 및 Docker Compose를 사용하여 실행됩니다. 아래 설명과 같이 Linux 가상 머신에 이 두 가지를 모두 설치해야 합니다.

또한 명령을 사용하여 RedHat에 VM을 등록해야 `sudo subscription-manager register` 합니다. 이 명령을 실행하면 계정 자격 증명을 입력하라는 메시지가 표시됩니다. 필요한 경우 \https://developers.redhat.com/.에서 계정을 만들 수 있습니다



== 1단계: Docker 설치 및 구성

RHEL 8 Linux 가상 머신에 Docker를 설치하고 구성합니다.

.단계
. 다음 명령을 사용하여 Docker 소프트웨어를 설치합니다.
+
[source, cli]
----
dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
dnf install docker-ce --nobest -y
----
. Docker를 시작하고 버전을 표시하여 설치가 성공적으로 완료되었는지 확인합니다.
+
[source, cli]
----
systemctl start docker
systemctl enable docker
docker --version
----
. 필요한 Linux 그룹을 관련 사용자와 추가합니다.
+
먼저 Linux 시스템에 * docker * 그룹이 있는지 확인하십시오. 그렇지 않으면 그룹을 만들고 사용자를 추가합니다. 기본적으로 현재 셸 사용자가 그룹에 추가됩니다.

+
[source, cli]
----
sudo groupadd docker
sudo usermod -aG docker $USER
----
. 새 그룹 및 사용자 정의를 활성화합니다
+
사용자와 함께 새 그룹을 만든 경우 정의를 활성화해야 합니다. 이렇게 하려면 Linux에서 로그아웃했다가 다시 로그인하거나 다음 명령을 실행할 수 있습니다.

+
[source, cli]
----
newgrp docker
----




== 2단계: Docker Compose 및 NFS 유틸리티 설치

Docker Compose를 NFS 유틸리티 패키지와 함께 설치 및 구성합니다.

.단계
. Docker를 설치하고 버전을 표시하여 설치가 성공적으로 완료되었는지 확인합니다.
+
[source, cli]
----
dnf install curl -y
curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
docker-compose --version
----
. NFS 유틸리티 패키지를 설치합니다.
+
[source, cli]
----
sudo yum install nfs-utils
----




== 3단계: Oracle 설치 파일을 다운로드합니다

필요한 Oracle 설치 및 패치 파일과 `azacsnap` 유틸리티를 다운로드합니다.

.단계
. 필요한 경우 Oracle 계정에 로그인합니다.
. 다음 파일을 다운로드합니다.
+
[cols="65,35"]
|===
| 파일 | 설명 


| LINUX.X64_193000_db_home.zip | 19.3 기본 장착 공구 


| p31281355_190000_Linux-x86-64.zip | 19.8RU 패치 


| p6880880_190000_Linux-x86-64.zip | OPatch 버전 12.2.0.1.23 


| azacsnap_installer_v5.0.ru n 을 참조하십시오 | azacsnap 설치 프로그램 
|===
. 모든 설치 파일을 폴더에 `/tmp/archive`넣습니다.
. 데이터베이스 서버의 모든 사용자가 폴더에 대한 모든 액세스 권한(읽기, 쓰기, 실행)을 갖는지 확인합니다. `/tmp/archive`




== 4단계: Docker 이미지 준비

자동화 솔루션과 함께 제공된 Docker 이미지를 추출하여 로드해야 합니다.

.단계
. 자동화 코드가 실행될 가상 머신에 솔루션 파일을 `na_oracle19c_deploy-master.zip` 복사합니다.
+
[source, cli]
----
scp -i ~/<private-key.pem> -r na_oracle19c_deploy-master.zip user@<IP_ADDRESS_OF_VM>
----
+
입력 매개 `private-key.pem` 변수는 Azure 가상 머신 인증에 사용되는 개인 키 파일입니다.

. 솔루션 파일이 있는 올바른 폴더로 이동하여 파일의 압축을 풉니다.
+
[source, cli]
----
unzip na_oracle19c_deploy-master.zip
----
. 압축 풀기 작업으로 생성된 새 폴더로 `na_oracle19c_deploy-master` 이동하여 파일을 나열합니다. 파일을 볼 수 `ora_anf_bck_image.tar` 있습니다.
+
[source, cli]
----
ls -lt
----
. Docker 이미지 파일을 로드합니다. 로드 작업은 일반적으로 몇 초 내에 완료됩니다.
+
[source, cli]
----
docker load -i ora_anf_bck_image.tar
----
. Docker 이미지가 로드되었는지 확인합니다.
+
[source, cli]
----
docker images
----
+
Docker `ora_anf_bck_image` 이미지와 태그가 `latest`표시됩니다.

+
[listing]
----
   REPOSITORY          TAG       IMAGE ID      CREATED      SIZE
ora_anf_bck_image    latest   ay98y7853769   1 week ago   2.58GB
----




== 5단계: 외부 볼륨을 만듭니다

Terraform 상태 파일과 기타 중요한 파일이 영구적으로 유지되도록 하려면 외부 볼륨이 필요합니다. Terraform에서 워크플로우 및 배포를 실행하려면 이러한 파일을 사용할 수 있어야 합니다.

.단계
. Docker Compose 외부에서 외부 볼륨을 생성합니다.
+
명령을 실행하기 전에 볼륨 이름을 업데이트하십시오.

+
[source, cli]
----
docker volume create <VOLUME_NAME>
----
. 다음 명령을 사용하여 외부 볼륨의 경로를 환경 파일에 추가합니다 `.env`.
+
`PERSISTENT_VOL=path/to/external/volume:/ora_anf_prov`..

+
기존 파일 내용과 콜론 서식을 유지해야 합니다. 예를 들면 다음과 같습니다.

+
[source, cli]
----
PERSISTENT_VOL= ora_anf _volume:/ora_anf_prov
----
. Terraform 변수를 업데이트합니다.
+
.. 폴더로 `ora_anf_variables`이동합니다.
.. 다음 두 파일이 있는지 `terraform.tfvars` 확인합니다. 및 `variables.tf`.
.. 사용자 환경에 필요한 대로 의 값을 `terraform.tfvars` 업데이트합니다.






== 6단계: Oracle을 설치합니다

이제 Oracle을 프로비저닝하고 설치할 수 있습니다.

.단계
. 다음 명령 시퀀스를 사용하여 Oracle을 설치합니다.
+
[source, cli]
----
docker-compose up terraform_ora_anf
bash /ora_anf_variables/setup.sh
docker-compose up linux_config
bash /ora_anf_variables/permissions.sh
docker-compose up oracle_install
----
. Bash 변수를 다시 로드하고 의 값을 표시하여 `ORACLE_HOME` 확인합니다.
+
.. `cd /home/oracle`
.. `source .bash_profile`
.. `echo $ORACLE_HOME`


. Oracle에 로그인할 수 있어야 합니다.
+
[source, cli]
----
sudo su oracle
----




== 7단계: Oracle 설치를 검증합니다

Oracle 설치가 성공적으로 완료되었는지 확인해야 합니다.

.단계
. Linux Oracle 서버에 로그인하고 Oracle 프로세스 목록을 표시합니다. 이렇게 하면 설치가 예상대로 완료되었고 Oracle 데이터베이스가 실행 중임을 확인할 수 있습니다.
+
[source, cli]
----
ps -ef | grep ora
----
. 데이터베이스에 로그인하여 데이터베이스 구성을 검사하고 PDB가 제대로 생성되었는지 확인합니다.
+
[source, cli]
----
sqlplus / as sysdba
----
+
다음과 유사한 출력이 표시됩니다.

+
[listing]
----
SQL*Plus: Release 19.0.0.0.0 - Production on Thu May 6 12:52:51 2021
Version 19.8.0.0.0

Copyright (c) 1982, 2019, Oracle. All rights reserved.

Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.8.0.0.0
----
. 몇 가지 간단한 SQL 명령을 실행하여 데이터베이스를 사용할 수 있는지 확인합니다.
+
[source, sql]
----
select name, log_mode from v$database;
show pdbs.
----




== 단계 8: azacsnap 유틸리티를 설치하고 스냅샷 백업을 수행합니다

스냅샷 백업을 수행하려면 유틸리티를 설치하고 실행해야 `azacsnap` 합니다.

.단계
. 컨테이너를 설치합니다.
+
[source, sql]
----
docker-compose up azacsnap_install
----
. 스냅샷 사용자 계정으로 전환합니다.
+
[source, sql]
----
su - azacsnap
execute /tmp/archive/ora_wallet.sh
----
. 스토리지 백업 세부 정보 파일을 구성합니다. 그러면 구성 파일이 `azacsnap.json` 생성됩니다.
+
[source, sql]
----
cd /home/azacsnap/bin/
azacsnap -c configure –-configuration new
----
. 스냅샷 백업을 수행합니다.
+
[source, sql]
----
azacsnap -c backup –-other data --prefix ora_test --retention=1
----




== 9단계: 필요에 따라 온프레미스 PDB를 클라우드로 마이그레이션합니다

필요에 따라 온프레미스 PDB를 클라우드로 마이그레이션할 수 있습니다.

.단계
. 환경에 필요한 대로 파일의 변수를 `tfvars` 설정합니다.
. PDB를 마이그레이션합니다.
+
[source, cli]
----
docker-compose -f docker-compose-relocate.yml up
----

