---
sidebar: sidebar 
permalink: solutions/bac-overview.html 
keywords: bluexp automation catalog, automation catalog, overview, introduction 
summary: NetApp 콘솔 자동화 카탈로그는 NetApp 고객, 파트너 및 직원이 사용할 수 있는 자동화 솔루션 모음입니다.  카탈로그에는 여러 가지 기능과 이점이 있습니다. 
---
= NetApp 콘솔 자동화 카탈로그 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp 콘솔 자동화 카탈로그는 NetApp 고객, 파트너 및 직원이 사용할 수 있는 자동화 솔루션 모음입니다.  카탈로그에는 여러 가지 기능과 이점이 있습니다.

자동화를 위한 단일 위치:: 당신은 접근할 수 있습니다 https://console.netapp.com/automationCatalog["NetApp 콘솔 자동화 카탈로그"^] 콘솔 웹 사용자 인터페이스를 통해.  이를 통해 NetApp 제품과 서비스의 자동화와 운영을 개선하는 데 필요한 스크립트, 플레이북, 모듈을 단일 위치에서 관리할 수 있습니다.
솔루션은 NetApp에서 만들고 테스트합니다:: 모든 자동화 솔루션과 스크립트는 NetApp에 의해 생성 및 테스트되었습니다. 각 솔루션은 특정 고객 사용 사례 또는 요청을 대상으로 합니다. 대부분 NetApp 파일 및 데이터 서비스와의 통합에 중점을 둡니다.
문서화:: 각 자동화 솔루션에는 시작하는 데 도움이 되는 관련 문서가 포함되어 있습니다.  솔루션은 콘솔 웹 인터페이스를 통해 접근하지만 모든 문서는 이 사이트에서 확인할 수 있습니다.  문서는 NetApp 제품과 클라우드 서비스를 기준으로 구성됩니다.
미래를 위한 견고한 기반:: NetApp 고객이 데이터 센터와 클라우드 환경의 자동화를 개선하고 간소화하도록 지원하는 데 전념하고 있습니다.  고객 요구 사항, 기술 변화, 지속적인 제품 통합에 대응하기 위해 콘솔 자동화 카탈로그를 지속적으로 개선해 나갈 예정입니다.
NetApp은 파트너 의견을 환영합니다:: NetApp 고객 경험 사무소(CXO) 자동화 팀이 연락을 드리면 됩니다. 피드백, 문제 또는 기능 요청이 있는 경우 mailto:ng-cxo-automation-administrators@NetApp.com[cXO 자동화 팀] 으로 이메일을 보내주시기 바랍니다.

