---
sidebar: sidebar 
permalink: solutions/ontap-day01-prepare.html 
keywords: bluexp automation catalog, netapp automation solutions, ontap day 0/1, prepare 
summary: 자동화 솔루션을 구축하기 전에 ONTAP 환경을 준비하고 Ansible을 설치 및 구성해야 합니다. 
---
= ONTAP Day 0/1 솔루션을 사용할 준비를 하십시오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
자동화 솔루션을 구축하기 전에 ONTAP 환경을 준비하고 Ansible을 설치 및 구성해야 합니다.



== 초기 계획 고려 사항

이 솔루션을 사용하여 ONTAP 클러스터를 구축하기 전에 다음 요구 사항 및 고려 사항을 검토해야 합니다.

.기본 요구 사항
이 솔루션을 사용하려면 다음 기본 요구 사항을 충족해야 합니다.

* 온프레미스 또는 ONTAP 시뮬레이터를 통해 ONTAP 소프트웨어에 액세스할 수 있어야 합니다.
* ONTAP 소프트웨어 사용 방법을 알고 있어야 합니다.
* Ansible 자동화 소프트웨어 툴을 사용하는 방법을 알아야 합니다.


.계획 고려 사항
이 자동화 솔루션을 배포하기 전에 다음을 결정해야 합니다.

* Ansible 제어 노드를 실행할 위치입니다.
* ONTAP 시스템의 온프레미스 하드웨어 또는 ONTAP 시뮬레이터입니다.
* 사용자 지정 필요 여부.




== ONTAP 시스템을 준비합니다

온프레미스 ONTAP 시스템을 사용하든 ONTAP를 시뮬레이션하든 상관없이 자동화 솔루션을 구축하기 전에 환경을 준비해야 합니다.



=== 필요에 따라 Simulate ONTAP를 설치 및 구성합니다

ONTAP 시뮬레이터를 통해 이 솔루션을 배포하려면 Simulate ONTAP를 다운로드하여 실행해야 합니다.

.시작하기 전에
* Simulate ONTAP를 실행하는 데 사용할 VMware 하이퍼바이저를 다운로드하고 설치해야 합니다.
+
** Windows 또는 Linux OS를 사용하는 경우 VMware Workstation을 사용하십시오.
** Mac OS를 사용하는 경우 VMware Fusion를 사용합니다.
+

NOTE: Mac OS를 사용하는 경우 Intel 프로세서가 있어야 합니다.





.단계
로컬 환경에 두 개의 ONTAP 시뮬레이터를 설치하려면 다음 절차를 따르십시오.

. 에서 Simulate ONTAP 를 link:https://mysupport.netapp.com/site/tools/tool-eula/simulate-ontap["NetApp Support 사이트"^]다운로드합니다.
+

NOTE: 두 개의 ONTAP 시뮬레이터를 설치하더라도 소프트웨어 복사본 하나만 다운로드하면 됩니다.

. 아직 실행 중이 아닌 경우 VMware 애플리케이션을 시작합니다.
. 다운로드한 시뮬레이터 파일을 찾아 마우스 오른쪽 버튼을 클릭하여 VMware 애플리케이션에서 엽니다.
. 첫 번째 ONTAP 인스턴스의 이름을 설정합니다.
. 시뮬레이터가 부팅될 때까지 기다린 다음 지침에 따라 단일 노드 클러스터를 생성합니다.
+
두 번째 ONTAP 인스턴스에 대해 이 단계를 반복합니다.

. 필요에 따라 전체 디스크 보완을 추가합니다.
+
각 클러스터에서 다음 명령을 실행합니다.

+
[source, cli]
----
security unlock -username <user_01>
security login password -username <user_01>
set -priv advanced
systemshell local
disk assign -all -node <Cluster-01>-01
----




=== ONTAP 시스템의 상태입니다

사내 시스템 또는 ONTAP 시뮬레이터를 통해 ONTAP 시스템의 초기 상태를 확인해야 합니다.

다음 ONTAP 시스템 요구 사항이 충족되는지 확인합니다.

* 아직 정의된 클러스터가 없는 상태에서 ONTAP가 설치되고 실행 중입니다.
* ONTAP가 부팅되고 클러스터에 액세스하기 위한 IP 주소가 표시됩니다.
* 네트워크에 연결할 수 있습니다.
* 관리자 자격 증명이 있습니다.
* MOTD(Message of the Day) 배너에 관리 주소가 표시됩니다.




== 필요한 자동화 소프트웨어를 설치합니다

이 섹션에서는 Ansible을 설치하고 구축을 위한 자동화 솔루션을 준비하는 방법에 대한 정보를 제공합니다.



=== Ansible 설치

Linux 또는 Windows 시스템에 Ansible을 설치할 수 있습니다.

Ansible이 ONTAP 클러스터와 통신하기 위해 사용하는 기본 통신 방법은 SSH입니다.

Ansible 설치에 대해서는 을 link:https://netapp.io/2018/10/08/getting-started-with-netapp-and-ansible-install-ansible/["NetApp 및 Ansible 시작하기: Ansible을 설치하십시오"^]참조하십시오.


NOTE: 시스템의 제어 노드에 Ansible을 설치해야 합니다.



=== 자동화 솔루션을 다운로드하고 준비합니다

다음 단계에 따라 배포를 위한 자동화 솔루션을 다운로드하고 준비할 수 있습니다.

. link:https://console.bluexp.netapp.com/automationCatalog["ONTAP - 1일차 및 1일차; 상태 점검"^]BlueXP  웹 UI를 통해 자동화 솔루션을 다운로드합니다. 솔루션은 다음과 같이 패키지되어 있습니다. `ONTAP_DAY0_DAY1.zip`
. zip 폴더의 압축을 풀고 Ansible 환경 내의 제어 노드에서 원하는 위치로 파일을 복사합니다.




== 초기 Ansible 프레임워크 구성

Ansible 프레임워크의 초기 구성 수행:

. 로 이동합니다 `playbooks/inventory/group_vars/all`.
. 파일 암호 해독 `vault.yml`:
+
`ansible-vault decrypt playbooks/inventory/group_vars/all/vault.yml`

+
볼트 암호를 입력하라는 메시지가 나타나면 다음 임시 암호를 입력합니다.

+
`NetApp123!`

+

IMPORTANT: "NetApp123!"는 파일과 해당 볼트 암호를 해독하기 위한 임시 암호입니다. `vault.yml` 처음 사용한 후에는 * 자신의 암호를 사용하여 * 파일을 암호화해야 합니다.

. 다음 Ansible 파일을 수정합니다.
+
** `clusters.yml` - 환경에 맞게 이 파일의 값을 수정합니다.
** `vault.yml` - 파일을 해독한 후 사용자 환경에 맞게 ONTAP 클러스터, 사용자 이름 및 암호 값을 수정합니다.
** `cfg.yml` - 에 대한 파일 경로를 `log2file` 설정하고 `cfg` 을(를) 표시하려면 을 `raw_service_request`(를 `True`) 로 설정합니다 `show_request`.
+
 `raw_service_request`로그 파일과 실행 중에 변수가 표시됩니다.

+

NOTE: 나열된 각 파일에는 요구 사항에 따라 수정하는 방법에 대한 지침이 포함된 설명이 포함되어 있습니다.



. 파일 다시 암호화 `vault.yml`:
+
`ansible-vault encrypt playbooks/inventory/group_vars/all/vault.yml`

+

NOTE: 암호화 시 볼트에 대한 새 암호를 선택하라는 메시지가 표시됩니다.

. 유효한 Python 인터프리터를 찾아 `playbooks/inventory/hosts` 설정합니다.
. 서비스 구축 `framework_test`:
+
다음 명령을 실행하면 `na_ontap_info` 값이 인 `cluster_identity_info` 모듈이 `gather_subset` 실행됩니다. 이렇게 하면 기본 구성이 올바른지 확인하고 클러스터와 통신할 수 있는지 확인합니다.

+
[source, cli]
----
ansible-playbook -i inventory/hosts site.yml -e cluster_name=<CLUSTER_NAME>
-e logic_operation=framework-test
----
+
각 클러스터에 대해 명령을 실행합니다.

+
성공하면 다음 예와 유사한 출력이 표시됩니다.

+
[listing]
----
PLAY RECAP *********************************************************************************
localhost : ok=12 changed=1 unreachable=0 failed=0 skipped=6
The key is ‘rescued=0’ and ‘failed=0’..
----

