---
sidebar: sidebar 
permalink: api/aiqum.html 
keywords: active iq, unified manager, active iq unified manager 
summary: 'Active IQ Unified Manager(이전의 OnCommand Unified Manager)는 ONTAP 시스템을 위한 포괄적인 관리 및 모니터링을 제공합니다. 또한 REST API가 포함되어 있어 이러한 작업을 자동화하고 지원 시스템에서 타사 통합을 지원할 수 있습니다.' 
---
= Active IQ Unified Manager
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Active IQ Unified Manager(이전의 OnCommand Unified Manager)는 ONTAP 시스템을 위한 포괄적인 관리 및 모니터링을 제공합니다. 또한 REST API가 포함되어 있어 이러한 작업을 자동화하고 지원 시스템에서 타사 통합을 지원할 수 있습니다.



== REST API의 이점

Active IQ Unified Manager와 함께 제공되는 REST API를 사용할 경우 몇 가지 이점이 있습니다.

.강력한 기능
REST API를 사용하면 Active IQ Unified Manager 기능에 액세스하여 스토리지 가용성, 용량, 보안, 보호 및 성능 위험을 관리할 수 있습니다.

.자동화 통합
워크로드를 프로비저닝하고 관리하는 데 단일 REST 엔드포인트를 사용할 수 있습니다. 이는 서비스 수준 목표 정책을 구현하고, 이벤트를 타사 툴로 리디렉션하고, API 게이트웨이 역할을 수행하여 개별 클러스터 수준에서 ONTAP REST API에 액세스할 수 있는 간단한 통합 접근 방식을 제공합니다.

.ONTAP 관리의 데이터 센터 수준 자동화
데이터 센터 수준에서 ONTAP 프로비저닝 및 관리 워크플로우를 자동화할 수 있습니다. 모니터링 및 보고도 자동화할 수 있습니다. 따라서 효율성이 향상되고 데이터 센터 수준 집계를 위한 기반이 마련됩니다.



== 자세한 정보를 확인하십시오

Active IQ Unified Manager REST API를 시작하는 데 도움이 되는 몇 가지 리소스가 있습니다.

* https://docs.netapp.com/us-en/active-iq-unified-manager/api-automation/concept_get_started_with_um_apis.html["Active IQ Unified Manager REST API 시작하기"^]
* https://library.netapp.com/ecmdocs/ECMLP2876865/html/index.html["Active IQ Unified Manager API 설명서"^]
* https://github.com/NetApp/Ansible-with-Active-IQ-Unified-Manager["Ansible용 NetApp 모듈"^]

